name: Playwright Tests
on:
  pull_request:
    branches: [main]
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Playwright Browsers
        run: |
          yarn install
          yarn playwright install --with-deps

      - name: Build Docker image
        run: docker build -t my-rails-app  -f Dockerfile.ci --build-arg REDIS_URL=redis://redis:${{ job.services.redis.env.REDIS_HOST }}:${{ job.services.redis.env.REDIS_PORT }} .

      - name: Start Rails server
        run: docker run -d -p 3000:3000  my-rails-app

      - name: Wait for server to start
        run: sleep 10

      - name: Run Playwright tests
        run: yarn playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ secrets.PLAYWRIGHT_TEST_BASE_URL }}
          CI_TEST_API_KEY: ${{ secrets.CI_TEST_API_KEY }}

      - name: Stop Rails server
        run: docker stop $(docker ps -q --filter ancestor=my-rails-app)

      - name: Clean up Docker containers
        run: docker system prune --force

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
